sample_menu_items = {
    "Appetizers": [
        "Bruschetta",
        "Caprese Salad",
        "Garlic Bread",
        "Stuffed Mushrooms",
        "Chicken Wings",
        "Potato Skins",
        "Shrimp Cocktail",
        "Nachos",
        "Crispy Calamari",
        "Spinach Artichoke Dip",
    ],
    "Breakfast": [
        "Buttermilk Pancakes",
        "French Toast",
        "Eggs Benedict",
        "Omelette",
        "Bacon and Eggs",
        "Breakfast Burrito",
        "Bagel with Cream Cheese",
        "Granola with Yogurt",
        "Smoothie Bowl",
        "Avocado Toast",
    ],
    "Soup": [
        "Tomato Soup",
        "Chicken Noodle Soup",
        "Minestrone",
        "French Onion Soup",
        "Clam Chowder",
        "Lentil Soup",
        "Butternut Squash Soup",
        "Vegetable Soup",
        "Miso Soup",
        "Gazpacho",
    ],
    "Salads": [
        "Caesar Salad",
        "Greek Salad",
        "Cobb Salad",
        "Spinach Salad",
        "Kale Salad",
        "Caprese Salad",
        "Waldorf Salad",
        "Nicoise Salad",
        "Mixed Greens Salad",
        "Quinoa Salad",
    ],
    "Seafood": [
        "Grilled Salmon",
        "Fish and Chips",
        "Shrimp Scampi",
        "Lobster Roll",
        "Tuna Tartare",
        "Seafood Paella",
        "Crab Cakes",
        "Seared Scallops",
        "Fish Tacos",
        "Cioppino",
    ],
    "Lunch": [
        "BLT Sandwich",
        "Grilled Cheese Sandwich",
        "Turkey Club Sandwich",
        "Chicken Caesar Wrap",
        "Veggie Burger",
        "Tuna Salad Sandwich",
        "Reuben Sandwich",
        "Pulled Pork Sandwich",
        "Chicken Pesto Panini",
        "Quiche",
    ],
    "House Specialties": [
        "Beef Wellington",
        "Coq au Vin",
        "Osso Buco",
        "Ratatouille",
        "Lamb Shank",
        "Stuffed Bell Peppers",
        "Veal Marsala",
        "Duck Confit",
        "Pork Tenderloin",
        "Chicken Piccata",
    ],
    "Dinner": [
        "Spaghetti Bolognese",
        "Chicken Alfredo",
        "Beef Stroganoff",
        "Vegetable Stir-Fry",
        "Eggplant Parmesan",
        "Chicken Curry",
        "Mushroom Risotto",
        "Fish en Papillote",
        "Shrimp and Grits",
        "Tofu Pad Thai",
    ],
    "Side Order": [
        "French Fries",
        "Mashed Potatoes",
        "Steamed Vegetables",
        "Green Beans Almondine",
        "Roasted Brussels Sprouts",
        "Coleslaw",
        "Garlic Knots",
        "Rice Pilaf",
        "Baked Sweet Potato",
        "Macaroni and Cheese",
    ],
    "Dessert": [
        "Chocolate Cake",
        "Tiramisu",
        "Apple Pie",
        "Cheesecake",
        "Creme Brulee",
        "Panna Cotta",
        "Bread Pudding",
        "Chocolate Chip Cookies",
        "Brownies",
        "Ice Cream Sundae",
    ],
    "Drinks": [
        "Coca-Cola",
        "Sprite",
        "Iced Tea",
        "Lemonade",
        "Orange Juice",
        "Coffee",
        "Espresso",
        "Cappuccino",
        "Hot Chocolate",
        "Milkshake",
    ],
}

sample_menus = [
    "Daily",
    "Weekend",
    "Brunch",
    "Dinner",
    "Mother's Day",
    "Spring",
    "Summer",
    "Winter",
    "Christmas Day",
    "Valentine's Day",
]
