FROM python:3.9

ENV PTYHONBUFFERED 1

RUN apt update && apt install nginx -y

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY . .

RUN pip install -r requirements.txt

WORKDIR /project
COPY ./nginx/run.sh .

RUN chmod +x run.sh
CMD ["./run.sh"]