# Generated by Django 4.2.2 on 2023-08-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_adminuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
